version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/treinepass
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - treinepass-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - treinepass-network

networks:
  treinepass-network:
    driver: bridge
